### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [user5497/PY202309#1]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/function
    - 29:Undefined variable 'lotto'	    same_numbers=set(user_inputs) & set(lotto) 
         -  함수 내 lotto 변수가 없습니다. 매개변수로 받아오거나, 전역 변수로 설정하세요. 
    - 27:Unused argument 'lotto_numbers'	def match_numbers(user_inputs,lotto_numbers):
        -  함수에서 lotto_numbers가 사용되고 있지 않습니다. 해당 매개변수를 제거하거나 사용하세요. 
- WARNING in project/week8/search_engine
    - 29:Unused variable 'sentences_set'	        sentences_set = set(preprocessed_sentences[i]) # set으로 전환
        - sentences_set이 사용되고 있지 않습니다.

**Comment by user5497** [comment]
해결했습니다
